generate_dataset: True
train_network: True
resume_training: True

paths:
  root: ''
  original_dataset: resources/datasets/rvl-cdip/mini-dataset-1600-200-200.h5
  cnn_dataset: resources/datasets/rvl-cdip/cnn-mini-dataset-1600-200-200.h5
  cnn_model: resources/models/model.json
  cnn_weights: resources/models/weights.h5
  cnn_weights_checkpoint: resources/checkpoints/checkpoint_weights.h5
  history_stats: resources/history/history_stats.csv
  log_file: resources/log.log

original_img_shape:
  - 1000
  - 750

cnn_image_shape:
  - 500
  - 375

n_classes: 16
